package com.pf.model.entity;
// Generated 2013-12-26 17:52:45 by Hibernate Tools 3.2.2.GA


import com.opensymphony.xwork2.conversion.annotations.TypeConversion;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TBill generated by hbm2java
 */
@Entity
@Table(name="t_bill"
    ,catalog="personalfinancial"
)
public class TBill  implements java.io.Serializable {


     private int billId;
     private TUser TUser;
     private String billStyle;
     private BigDecimal billMoney;
     private Date billCraetedTime;
     private String billMemo;

    public TBill() {
    }

	
    public TBill(int billId) {
        this.billId = billId;
    }
    public TBill(int billId, TUser TUser, String billStyle, BigDecimal billMoney, Date billCraetedTime, String billMemo) {
       this.billId = billId;
       this.TUser = TUser;
       this.billStyle = billStyle;
       this.billMoney = billMoney;
       this.billCraetedTime = billCraetedTime;
       this.billMemo = billMemo;
    }
   
     @Id 
    
    @Column(name="BILL_ID", unique=true, nullable=false)
    public int getBillId() {
        return this.billId;
    }
    
    public void setBillId(int billId) {
        this.billId = billId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public TUser getTUser() {
        return this.TUser;
    }
    
    public void setTUser(TUser TUser) {
        this.TUser = TUser;
    }
    
    @Column(name="BILL_STYLE", length=30)
    public String getBillStyle() {
        return this.billStyle;
    }
    
    public void setBillStyle(String billStyle) {
        this.billStyle = billStyle;
    }
    
    @Column(name="BILL_MONEY", precision=10)
    public BigDecimal getBillMoney() {
        return this.billMoney;
    }
    
    public void setBillMoney(BigDecimal billMoney) {
        this.billMoney = billMoney;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BILL_CRAETED_TIME", length=19)
    public Date getBillCraetedTime() {
        return this.billCraetedTime;
    }
//    @TypeConversion(converter = "struts.DateConverter")
    public void setBillCraetedTime(Date billCraetedTime) {
        this.billCraetedTime = billCraetedTime;
    }
    
    @Column(name="BILL_MEMO")
    public String getBillMemo() {
        return this.billMemo;
    }
    
    public void setBillMemo(String billMemo) {
        this.billMemo = billMemo;
    }




}


