package com.pf.model.entity;
// Generated 2013-12-26 17:52:45 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name="t_user"
    ,catalog="personalfinancial"
)
public class TUser  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String userPasswd;
     private Set TBills = new HashSet(0);

    public TUser() {
    }

	
    public TUser(int userId) {
        this.userId = userId;
    }
    public TUser(int userId, String userName, String userPasswd, Set TBills) {
       this.userId = userId;
       this.userName = userName;
       this.userPasswd = userPasswd;
       this.TBills = TBills;
    }
   
     @Id 
    
    @Column(name="USER_ID", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    
    @Column(name="USER_NAME")
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="USER_PASSWD")
    public String getUserPasswd() {
        return this.userPasswd;
    }
    
    public void setUserPasswd(String userPasswd) {
        this.userPasswd = userPasswd;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="TUser")
    public Set getTBills() {
        return this.TBills;
    }
    
    public void setTBills(Set TBills) {
        this.TBills = TBills;
    }




}


